/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diplo;

import java.awt.Graphics;
import java.awt.MouseInfo;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Alibimunka
 */
public class Alaprajz extends javax.swing.JFrame {
    
    private int mode = 0;
    
    /**
     * mode 0 = init
     * mode 1 = felvitel
     * mode 2 = lekérdezés
     */
    
    int x,y;
    
    public class termek {
        private int elerheto;

        public int getElerheto() {
            return elerheto;
        }

        public void setElerheto(int elerheto) {
            this.elerheto = elerheto;
        }

        public String getNev() {
            return nev;
        }

        public void setNev(String nev) {
            this.nev = nev;
        }
        private String nev;
        termek(String szoveg, int szam){
            this.elerheto = szam;
            this.nev=szoveg;
        }
        termek(){
            this.elerheto = 0;
            this.nev = "nincs adat";
        }
    }
    
    termek[][] adatok = new termek[50][50];
    
    
    
    /**
     * Creates new form Alaprajz
     */
    public Alaprajz() throws FileNotFoundException, IOException {
        initComponents();
        
        ImagePanel newImage = new ImagePanel();
        HatterLabel.add(newImage);

        for (int i=0;i<50;i++){
            for (int j=0;j<50;j++){
                adatok[i][j]= new termek();
            }
        }
        
    }

    public class ImagePanel extends JPanel{

        private BufferedImage image;

        public ImagePanel() {
           try {                
              image = ImageIO.read(new File("teszt"));
           } catch (IOException ex) {
                // handle exception...
           }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image, 0, 0, this); // see javadoc for more info on the parameters            
        }

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FelvitelButton = new javax.swing.JButton();
        LekerButton = new javax.swing.JButton();
        HatterLabel = new javax.swing.JLabel();
        BeTextField = new javax.swing.JTextField();
        KiTextField = new javax.swing.JTextField();
        ErrorLabel = new javax.swing.JLabel();
        ModButton = new javax.swing.JButton();
        ModTextField = new javax.swing.JTextField();
        TorlesButton = new javax.swing.JButton();
        KeresesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KerY = new javax.swing.JTextField();
        KerX = new javax.swing.JTextField();
        KeresesTextField = new javax.swing.JTextField();
        ImportButton = new javax.swing.JButton();
        ExportButton = new javax.swing.JButton();
        FilenameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FelvitelButton.setText("Felvitel");
        FelvitelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FelvitelButtonActionPerformed(evt);
            }
        });

        LekerButton.setText("Lekérés");
        LekerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LekerButtonActionPerformed(evt);
            }
        });

        HatterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diplo/teszt.jpg"))); // NOI18N
        HatterLabel.setMaximumSize(new java.awt.Dimension(600, 600));
        HatterLabel.setMinimumSize(new java.awt.Dimension(400, 400));
        HatterLabel.setPreferredSize(new java.awt.Dimension(500, 500));
        HatterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HatterLabelMouseClicked(evt);
            }
        });

        BeTextField.setText("Termék neve");

        ModButton.setText("Módosítás");
        ModButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModButtonActionPerformed(evt);
            }
        });

        TorlesButton.setText("Törlés");
        TorlesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TorlesButtonActionPerformed(evt);
            }
        });

        KeresesButton.setText("Keresés");
        KeresesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeresesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("x:");

        jLabel2.setText("y:");

        ImportButton.setText("Import");
        ImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportButtonActionPerformed(evt);
            }
        });

        ExportButton.setText("Export");
        ExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportButtonActionPerformed(evt);
            }
        });

        FilenameTextField.setText("File neve");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImportButton)
                        .addGap(18, 18, 18)
                        .addComponent(ExportButton)
                        .addGap(41, 41, 41)
                        .addComponent(FilenameTextField))
                    .addComponent(HatterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(KiTextField)
                                    .addComponent(ModTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TorlesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LekerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FelvitelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KeresesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KeresesTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(KerY))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(KerX, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 96, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HatterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImportButton)
                            .addComponent(ExportButton)
                            .addComponent(FilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FelvitelButton)
                            .addComponent(BeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LekerButton)
                            .addComponent(KiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModButton)
                            .addComponent(ModTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TorlesButton)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KeresesButton)
                            .addComponent(KeresesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void FelvitelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FelvitelButtonActionPerformed
        // TODO add your handling code here:
        mode = 1;
    }//GEN-LAST:event_FelvitelButtonActionPerformed

    private void LekerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LekerButtonActionPerformed
        // TODO add your handling code here:
        mode = 2;
    }//GEN-LAST:event_LekerButtonActionPerformed

    private void HatterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HatterLabelMouseClicked
        // TODO add your handling code here:
        int xcor = MouseInfo.getPointerInfo().getLocation().x - HatterLabel.getLocationOnScreen().x;
        int ycor = MouseInfo.getPointerInfo().getLocation().y - HatterLabel.getLocationOnScreen().y;
        x = xcor/10;
        y = ycor/10;
        System.out.println(x*10+":"+y*10);
        switch (mode) {
            case 1:  {
                adatok[x][y] = new termek(BeTextField.getText(),1);
                break;
            }
            case 2:  {
                if (adatok[x][y].getElerheto()==1) KiTextField.setText(adatok[x][y].getNev());
                else KiTextField.setText("Nincs adat");
                break;
            }
            default: System.out.println("Not a month!"); break;
        }
    }//GEN-LAST:event_HatterLabelMouseClicked

    private void ModButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModButtonActionPerformed
        // TODO add your handling code here:
        adatok[x][y].setNev(ModTextField.getText());
    }//GEN-LAST:event_ModButtonActionPerformed

    private void TorlesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorlesButtonActionPerformed
        // TODO add your handling code here:
        adatok[x][y].setElerheto(0);
    }//GEN-LAST:event_TorlesButtonActionPerformed

    private void KeresesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeresesButtonActionPerformed
        // TODO add your handling code here:
        String keresett = KeresesTextField.getText();
        for (int i=0;i<50;i++){
            for (int j=0;j<50;j++){
                if (adatok[i][j].getNev() == null ? keresett == null : adatok[i][j].getNev().equals(keresett)){
                    KerX.setText(Integer.toString(i));
                    KerY.setText(Integer.toString(j));
                }
            }
        }
        
    }//GEN-LAST:event_KeresesButtonActionPerformed

    private void ImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportButtonActionPerformed
        BufferedReader br = null;
        try {
            // TODO add your handling code here:
            File file = new File(FilenameTextField.getText());
            br = new BufferedReader(new FileReader(file));
            String s;
            while ((s = br.readLine()) != null){
                String[] parts = s.split("\t");
                Integer[] szamok = new Integer[3];
                for (Integer i=0;i<3;i++){
                    szamok[i]=Integer.parseInt(parts[i]);
                }
                adatok[szamok[0]][szamok[1]].setElerheto(szamok[2]);
                adatok[szamok[0]][szamok[1]].setNev(parts[3]);
            }
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Alaprajz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Alaprajz.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(Alaprajz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ImportButtonActionPerformed

    private void ExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportButtonActionPerformed
        
        BufferedWriter writer = null;
        try {
            // TODO add your handling code here:
            writer = new BufferedWriter(new FileWriter(FilenameTextField.getText()));
            for (int i=0;i<50;i++){
                for (int j=0;j<50;j++){
                    if (adatok[i][j].getElerheto()==1){
                        String szovegki="\n";
                        szovegki=i+"\t"+j+"\t"+1+"\t"+adatok[i][j].getNev()+"\n";
                        writer.write(szovegki);
                    }
                }
            }
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Alaprajz.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(Alaprajz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ExportButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alaprajz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alaprajz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alaprajz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alaprajz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Alaprajz().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Alaprajz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BeTextField;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton ExportButton;
    private javax.swing.JButton FelvitelButton;
    private javax.swing.JTextField FilenameTextField;
    private javax.swing.JLabel HatterLabel;
    private javax.swing.JButton ImportButton;
    private javax.swing.JTextField KerX;
    private javax.swing.JTextField KerY;
    private javax.swing.JButton KeresesButton;
    private javax.swing.JTextField KeresesTextField;
    private javax.swing.JTextField KiTextField;
    private javax.swing.JButton LekerButton;
    private javax.swing.JButton ModButton;
    private javax.swing.JTextField ModTextField;
    private javax.swing.JButton TorlesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
